actions:
  post-upstream-clone:
    - './autogen.sh'
    - './configure'
  create-archive:
    - 'make'
    - 'make local'
    - 'bash -c "ls *.tar*"'
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all-x86_64
    - fedora-all-ppc64le
    - fedora-all-x86_64
    - epel-8-aarch64
    - epel-8-ppc64le
    - epel-8-x86_64
    - epel-9-aarch64
    - epel-9-ppc64le
    - epel-9-x86_64
  trigger: pull_request
srpm_build_deps:
 - make
 - gcc
 - libtool
 - autoconf
 - automake
 - gmp-devel
 - mpfr-devel
 - pcre2-devel
 - gettext-devel
 - python3-devel
 - gtk-doc

downstream_package_name: libbytesize
specfile_path: dist/libbytesize.spec
