name: Run static analysis using csmock

env:
  CSMOCK_CHROOTS: "default"
  CSMOCK_TOOLS: "clang cppcheck gcc"

on:
  pull_request:
    branches:
     - master

jobs:
  build:
    name: csmock
    runs-on: ubuntu-22.04
    env:
      CI_CONTAINER: libbytesize-ci-csmock
    steps:
      - name: Checkout libbytesize repository
        uses: actions/checkout@v3

      - name: Install podman
        run: |
          sudo apt -qq update
          sudo apt -y -qq install podman

      - name: Build the container
        run: |
          sudo podman build --no-cache -t ${{ env.CI_CONTAINER }} -f misc/csmock.Dockerfile .

      - name: Run csmock build in the container
        run: |
          sudo podman run -i --rm --privileged --volume "$(pwd):/app" --workdir "/app" ${{ env.CI_CONTAINER }} <<EOF
          set -eux
          ansible-playbook -i "localhost," -c local misc/install-test-dependencies.yml
          /ci/run_csmock_tests -c /ci/copr-builder.conf -p libbytesize-udisks -t ${{ env.CSMOCK_TOOLS }} -r ${{ env.CSMOCK_CHROOTS }}
          EOF

      - name: Upload the csmock logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: csmock_logs
          path: csmock_*/*
